const SCORE_LABELS_WEALTH = ["", "Anxious", "Stressed", "Uneasy", "Uncertain", "Neutral", "Okay", "Hopeful", "Confident", "Abundant", "Unstoppable"];
const SCORE_LABELS_MOTIV  = ["", "Defeated", "Drained", "Flat", "Restless", "Neutral", "Stirring", "Driven", "Focused", "Fired Up", "Unstoppable"];
const SCORE_COLORS = ["", "#c94c4c", "#c96a4c", "#c9884c", "#c9a44c", "#a8a868", "#7ab86e", "#5cb87a", "#4cb89a", "#4caac9", "#f0c040"];

export const JOURNALS = {
  wealth: {
    id: 'wealth',
    name: 'Wealth Journal',
    icon: '◆',
    color: '#f0c040',
    colorRgb: '240,192,64',
    description: '90-day financial mindset practice',
    scoreLabels: SCORE_LABELS_WEALTH,
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How do you feel about money this morning?',
    scoreEveningQ: 'How do you feel about money right now, end of day?',
    trendTitle: 'Money Mindset Over Time',
    loftyQuestions: [
      "Why does wealth come to me so naturally?",
      "Why am I so good at spotting opportunity?",
      "Why does money flow to me from expected and unexpected sources?",
      "Why do I always have more than enough?",
      "Why is building wealth so enjoyable for me?",
      "Why do people gladly pay for the value I create?",
      "Why am I so confident with financial decisions?",
      "Why does abundance feel so normal to me?",
      "Why do the right opportunities find me at the right time?",
      "Why is it so easy for me to save and invest wisely?",
      "Why do I attract people who help me grow financially?",
      "Why does my income keep increasing?",
      "Why am I so good at turning ideas into income?",
      "Why do I deserve financial freedom?",
      "Why does my relationship with money keep getting healthier?",
      "Why am I so disciplined with wealth-building habits?",
      "Why does my net worth grow while I sleep?",
      "Why do I make money decisions from abundance, not fear?",
      "Why is generosity so natural when wealth flows to me?",
      "Why do I trust myself completely with large sums of money?",
      "Why do my skills become more valuable every year?",
      "Why is financial education so fascinating to me?",
      "Why do I see possibility where others see limitation?",
      "Why does every setback move me closer to a breakthrough?",
      "Why am I becoming the person who earns at the next level?",
      "Why do I release old money stories so easily?",
      "Why is wealth just a natural byproduct of who I'm becoming?",
      "Why do I take action on financial goals without hesitation?",
      "Why does compound growth work so powerfully in my favor?",
      "Why am I already wealthier than I was yesterday?",
    ],
    weeklyPrompts: [
      "Income Ceiling Audit: What number do you believe is 'the most someone like you' can earn? Who told you that?",
      "What did you learn about money, investing, or financial systems this week? One takeaway.",
      "'I don't deserve more money because...' — Write honestly, then write the counter-evidence.",
      "Write 3 sentences from you 5 years from now, looking back at this week.",
      "Top 3 ways you created value this week. Which has the most growth potential?",
      "If money were a person, how would you describe your relationship right now?",
      "What financial skill would change everything? What's your plan to learn it?",
      "What % of this week's spending went toward things that genuinely matter?",
      "Are you spending time with people who expand or shrink your financial vision?",
      "What are you most afraid of with money? Is that fear protecting or trapping you?",
      "One financial thing you used to dream about but now take for granted.",
      "If you HAD to 10x your income in 3 years, what changes starting Monday?",
      "Describe the person who naturally earns at the level you're building toward.",
    ],
    fieldMeta: {
      visualize: { label: "Visualize",        color: "#f0c040", icon: "☀" },
      gratitude:  { label: "Money Gratitude", color: "#7a4cc9", icon: "✦" },
      lofty_a:    { label: "Lofty Answer",    color: "#a8c94c", icon: "→" },
      value:      { label: "Value Created",   color: "#c97a4c", icon: "◆" },
      weekly:     { label: "Weekly Deep Dive",color: "#c94c6e", icon: "★" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "visualize", label: "Visualize",             q: "Close your eyes for 60 seconds. See one specific scene from the life you're building. Describe it.", color: "#f0c040", rows: 2 },
      { id: "gratitude", label: "Money Gratitude",       q: "3 financial things you're grateful for right now, no matter how small.", color: "#7a4cc9", rows: 3 },
      { id: "lofty_q",   label: "Today's Lofty Question",q: loftyQ, color: "#a8c94c", hint: "Sit with this question. Let your brain search for answers all day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "lofty_a", label: "Lofty Answer",    q: `Your brain has been working on this all day:\n\n"${loftyQ}"\n\nWhat answers did it find?`, color: "#a8c94c", rows: 2 },
      { id: "value",   label: "Value Created",   q: "How did you create value for others today?", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Deep Dive", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  motivational: {
    id: 'motivational',
    name: 'Motivational Journal',
    icon: '★',
    color: '#a8c94c',
    colorRgb: '168,201,76',
    description: 'Daily mindset, growth, and momentum',
    scoreLabels: SCORE_LABELS_MOTIV,
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How motivated and alive do you feel this morning?',
    scoreEveningQ: 'How driven and energized do you feel right now?',
    trendTitle: 'Motivation Over Time',
    loftyQuestions: [
      "Why do I keep showing up even when it's hard?",
      "Why is growth my natural state?",
      "Why am I so resilient?",
      "Why do I embrace discomfort as part of my progress?",
      "Why does consistency come naturally to me?",
      "Why do I believe in myself more every day?",
      "Why do my habits compound into extraordinary results?",
      "Why do I attract people who push me to grow?",
      "Why do I turn obstacles into opportunities?",
      "Why does discipline feel like freedom to me?",
      "Why am I becoming the best version of myself?",
      "Why do I complete what I start?",
      "Why is my potential limitless?",
      "Why do I show up fully every single day?",
      "Why does my mindset get stronger through challenges?",
      "Why do I choose growth over comfort?",
      "Why do I inspire others simply by becoming my best self?",
      "Why do I take full responsibility for my results?",
      "Why does momentum build naturally for me?",
      "Why am I exactly where I need to be right now?",
      "Why do small daily actions create massive change for me?",
      "Why do I trust the process even when results are slow?",
      "Why is my best always getting better?",
      "Why do I pursue excellence without waiting for perfect conditions?",
      "Why do I use every day as a chance to level up?",
    ],
    weeklyPrompts: [
      "What's one belief you're still letting limit you? How would you act if you dropped it?",
      "Rate your consistency this week 1–10. What would make it a 10 next week?",
      "Who in your life models the energy and discipline you want? What can you learn from them?",
      "What habit, if done daily for a year, would change your life most?",
      "Where did you choose comfort over growth this week? Was it worth it?",
      "What does your future self need you to do right now that your current self is avoiding?",
      "What's the difference between who you are now and who you're becoming?",
      "If you could give advice to yourself from 1 year ago, what would it be?",
      "What's the story you keep telling yourself that's holding you back? Rewrite it.",
      "Name one hard thing you did this week that you're proud of.",
      "What would you attempt if you knew you couldn't fail?",
      "Who do you need to become to achieve the goals you've set?",
    ],
    fieldMeta: {
      intention:  { label: "Today's Intention", color: "#f0c040", icon: "→" },
      affirmation:{ label: "Affirmation",        color: "#4caac9", icon: "✦" },
      wins:       { label: "Wins",               color: "#4cc97a", icon: "★" },
      learning:   { label: "Learning",           color: "#7a4cc9", icon: "◆" },
      tomorrow:   { label: "Tomorrow",           color: "#c97a4c", icon: "↑" },
      weekly:     { label: "Weekly Reflection",  color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "intention",   label: "Today's Intention", q: "What's the one thing that would make today a win? Be specific.", color: "#f0c040", rows: 2 },
      { id: "affirmation", label: "Affirmation",        q: "Complete this: I am becoming someone who...", color: "#4caac9", rows: 2 },
      { id: "lofty_q",     label: "Today's Question",   q: loftyQ, color: "#a8c94c", hint: "Let this question sit with you all day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "wins",     label: "Wins",              q: "List 3 wins from today — small or large, they all count.", color: "#4cc97a", rows: 3 },
      { id: "learning", label: "Learning",          q: "What did today teach you about yourself?", color: "#7a4cc9", rows: 2 },
      { id: "tomorrow", label: "Tomorrow",          q: "One thing you'll do better or differently tomorrow.", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Reflection", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  health: {
    id: 'health',
    name: 'Health Journal',
    icon: '♡',
    color: '#4cb89a',
    colorRgb: '76,184,154',
    description: 'Body, energy, and daily habits',
    comingSoon: true,
  },
};
