const SCORE_LABELS_WEALTH = ["", "Anxious", "Stressed", "Uneasy", "Uncertain", "Neutral", "Okay", "Hopeful", "Confident", "Abundant", "Unstoppable"];
const SCORE_LABELS_MOTIV  = ["", "Defeated", "Drained", "Flat", "Restless", "Neutral", "Stirring", "Driven", "Focused", "Fired Up", "Unstoppable"];
const SCORE_COLORS = ["", "#c94c4c", "#c96a4c", "#c9884c", "#c9a44c", "#a8a868", "#7ab86e", "#5cb87a", "#4cb89a", "#4caac9", "#f0c040"];

export const JOURNALS = {
  wealth: {
    id: 'wealth',
    name: 'Wealth Journal',
    icon: '◆',
    color: '#f0c040',
    colorRgb: '240,192,64',
    description: '90-day financial mindset practice',
    tagline: 'Where money meets meaning.',
    scoreLabels: SCORE_LABELS_WEALTH,
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How do you feel about money this morning?',
    scoreEveningQ: 'How do you feel about money right now, end of day?',
    trendTitle: 'Money Mindset Over Time',
    loftyQuestions: [
      "Why does wealth come to me so naturally?",
      "Why am I so good at spotting opportunity?",
      "Why does money flow to me from expected and unexpected sources?",
      "Why do I always have more than enough?",
      "Why is building wealth so enjoyable for me?",
      "Why do people gladly pay for the value I create?",
      "Why am I so confident with financial decisions?",
      "Why does abundance feel so normal to me?",
      "Why do the right opportunities find me at the right time?",
      "Why is it so easy for me to save and invest wisely?",
      "Why do I attract people who help me grow financially?",
      "Why does my income keep increasing?",
      "Why am I so good at turning ideas into income?",
      "Why do I deserve financial freedom?",
      "Why does my relationship with money keep getting healthier?",
      "Why am I so disciplined with wealth-building habits?",
      "Why does my net worth grow while I sleep?",
      "Why do I make money decisions from abundance, not fear?",
      "Why is generosity so natural when wealth flows to me?",
      "Why do I trust myself completely with large sums of money?",
      "Why do my skills become more valuable every year?",
      "Why is financial education so fascinating to me?",
      "Why do I see possibility where others see limitation?",
      "Why does every setback move me closer to a breakthrough?",
      "Why am I becoming the person who earns at the next level?",
      "Why do I release old money stories so easily?",
      "Why is wealth just a natural byproduct of who I'm becoming?",
      "Why do I take action on financial goals without hesitation?",
      "Why does compound growth work so powerfully in my favor?",
      "Why am I already wealthier than I was yesterday?",
    ],
    weeklyPrompts: [
      "Income Ceiling Audit: What number do you believe is 'the most someone like you' can earn? Who told you that?",
      "What did you learn about money, investing, or financial systems this week? One takeaway.",
      "'I don't deserve more money because...' — Write honestly, then write the counter-evidence.",
      "Write 3 sentences from you 5 years from now, looking back at this week.",
      "Top 3 ways you created value this week. Which has the most growth potential?",
      "If money were a person, how would you describe your relationship right now?",
      "What financial skill would change everything? What's your plan to learn it?",
      "What % of this week's spending went toward things that genuinely matter?",
      "Are you spending time with people who expand or shrink your financial vision?",
      "What are you most afraid of with money? Is that fear protecting or trapping you?",
      "One financial thing you used to dream about but now take for granted.",
      "If you HAD to 10x your income in 3 years, what changes starting Monday?",
      "Describe the person who naturally earns at the level you're building toward.",
    ],
    fieldMeta: {
      visualize: { label: "Visualize",        color: "#f0c040", icon: "☀" },
      gratitude:  { label: "Money Gratitude", color: "#7a4cc9", icon: "✦" },
      lofty_a:    { label: "Lofty Answer",    color: "#a8c94c", icon: "→" },
      value:      { label: "Value Created",   color: "#c97a4c", icon: "◆" },
      weekly:     { label: "Weekly Deep Dive",color: "#c94c6e", icon: "★" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "visualize", label: "Visualize",             q: "Close your eyes for 60 seconds. See one specific scene from the life you're building. Describe it.", color: "#f0c040", rows: 2 },
      { id: "gratitude", label: "Money Gratitude",       q: "3 financial things you're grateful for right now, no matter how small.", color: "#7a4cc9", rows: 3 },
      { id: "lofty_q",   label: "Today's Lofty Question",q: loftyQ, color: "#a8c94c", hint: "Sit with this question. Let your brain search for answers all day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "lofty_a", label: "Lofty Answer",    q: `Your brain has been working on this all day:\n\n"${loftyQ}"\n\nWhat answers did it find?`, color: "#a8c94c", rows: 2 },
      { id: "value",   label: "Value Created",   q: "How did you create value for others today?", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Deep Dive", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  motivational: {
    id: 'motivational',
    name: 'Motivational Journal',
    icon: '★',
    color: '#a8c94c',
    colorRgb: '168,201,76',
    description: 'Daily mindset, growth, and momentum',
    tagline: 'Build the mind that builds the life.',
    scoreLabels: SCORE_LABELS_MOTIV,
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How motivated and alive do you feel this morning?',
    scoreEveningQ: 'How driven and energized do you feel right now?',
    trendTitle: 'Motivation Over Time',
    loftyQuestions: [
      "Why do I keep showing up even when it's hard?",
      "Why is growth my natural state?",
      "Why am I so resilient?",
      "Why do I embrace discomfort as part of my progress?",
      "Why does consistency come naturally to me?",
      "Why do I believe in myself more every day?",
      "Why do my habits compound into extraordinary results?",
      "Why do I attract people who push me to grow?",
      "Why do I turn obstacles into opportunities?",
      "Why does discipline feel like freedom to me?",
      "Why am I becoming the best version of myself?",
      "Why do I complete what I start?",
      "Why is my potential limitless?",
      "Why do I show up fully every single day?",
      "Why does my mindset get stronger through challenges?",
      "Why do I choose growth over comfort?",
      "Why do I inspire others simply by becoming my best self?",
      "Why do I take full responsibility for my results?",
      "Why does momentum build naturally for me?",
      "Why am I exactly where I need to be right now?",
      "Why do small daily actions create massive change for me?",
      "Why do I trust the process even when results are slow?",
      "Why is my best always getting better?",
      "Why do I pursue excellence without waiting for perfect conditions?",
      "Why do I use every day as a chance to level up?",
    ],
    weeklyPrompts: [
      "What's one belief you're still letting limit you? How would you act if you dropped it?",
      "Rate your consistency this week 1–10. What would make it a 10 next week?",
      "Who in your life models the energy and discipline you want? What can you learn from them?",
      "What habit, if done daily for a year, would change your life most?",
      "Where did you choose comfort over growth this week? Was it worth it?",
      "What does your future self need you to do right now that your current self is avoiding?",
      "What's the difference between who you are now and who you're becoming?",
      "If you could give advice to yourself from 1 year ago, what would it be?",
      "What's the story you keep telling yourself that's holding you back? Rewrite it.",
      "Name one hard thing you did this week that you're proud of.",
      "What would you attempt if you knew you couldn't fail?",
      "Who do you need to become to achieve the goals you've set?",
    ],
    fieldMeta: {
      intention:  { label: "Today's Intention", color: "#f0c040", icon: "→" },
      affirmation:{ label: "Affirmation",        color: "#4caac9", icon: "✦" },
      wins:       { label: "Wins",               color: "#4cc97a", icon: "★" },
      learning:   { label: "Learning",           color: "#7a4cc9", icon: "◆" },
      tomorrow:   { label: "Tomorrow",           color: "#c97a4c", icon: "↑" },
      weekly:     { label: "Weekly Reflection",  color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "intention",   label: "Today's Intention", q: "What's the one thing that would make today a win? Be specific.", color: "#f0c040", rows: 2 },
      { id: "affirmation", label: "Affirmation",        q: "Complete this: I am becoming someone who...", color: "#4caac9", rows: 2 },
      { id: "lofty_q",     label: "Today's Question",   q: loftyQ, color: "#a8c94c", hint: "Let this question sit with you all day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "wins",     label: "Wins",              q: "List 3 wins from today — small or large, they all count.", color: "#4cc97a", rows: 3 },
      { id: "learning", label: "Learning",          q: "What did today teach you about yourself?", color: "#7a4cc9", rows: 2 },
      { id: "tomorrow", label: "Tomorrow",          q: "One thing you'll do better or differently tomorrow.", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Reflection", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  health: {
    id: 'health',
    name: 'Health Journal',
    icon: '♡',
    color: '#4cb89a',
    colorRgb: '76,184,154',
    description: 'Body, energy, and daily habits',
    tagline: 'Honor the body. Trust the process.',
    scoreLabels: ["", "Depleted", "Drained", "Heavy", "Sluggish", "Neutral", "Okay", "Energized", "Strong", "Vibrant", "Unstoppable"],
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How does your body feel this morning?',
    scoreEveningQ: 'How did your body hold up today?',
    trendTitle: 'Energy Over Time',
    loftyQuestions: [
      "Why does my body feel so strong and capable?",
      "Why does healthy living come naturally to me?",
      "Why do I crave movement and feel good after exercise?",
      "Why does my energy stay high throughout the day?",
      "Why do I sleep deeply and wake up refreshed?",
      "Why do I make food choices that nourish me?",
      "Why does my body recover so well?",
      "Why am I becoming healthier every single day?",
      "Why do I listen to and trust my body?",
      "Why does consistency with my health habits feel effortless?",
      "Why do I attract the energy and vitality I want?",
      "Why does my body naturally find its ideal state?",
      "Why do small healthy choices add up so powerfully for me?",
      "Why do I enjoy taking care of myself?",
      "Why does rest and recovery feel like strength?",
      "Why do I breathe deeply and move with ease?",
      "Why is building healthy habits one of my greatest investments?",
      "Why do I wake up excited to take care of my body today?",
      "Why does physical strength translate into mental strength for me?",
      "Why do I make time for movement no matter how busy I am?",
      "Why does hydration and nutrition come so naturally to me?",
      "Why do I feel more alive and vibrant each week?",
      "Why do I show up for my health even when motivation dips?",
      "Why does my body thank me when I treat it well?",
      "Why is long-term health my most important asset?",
    ],
    weeklyPrompts: [
      "How did your energy levels track this week? What patterns do you notice?",
      "What's one health habit that served you well — and one you want to strengthen?",
      "If your body could talk, what would it say to you right now?",
      "Where did you choose convenience over health? Was it worth it?",
      "What does 'feeling healthy' actually mean to you? Has that definition shifted?",
      "Rate your sleep quality this week 1–10. What would make it a 10 next week?",
      "What's one belief about your body that you're ready to let go of?",
      "How has your energy level shaped your mood and decisions this week?",
      "What would your life look like if you were at your physical best?",
      "Name one hard health habit you kept this week that you're proud of.",
      "What's the gap between how you want to feel and how you actually feel? What's the bridge?",
      "Who models the level of health and vitality you want? What can you learn from them?",
      "If you treated your body like your most prized possession, what would change?",
    ],
    fieldMeta: {
      movement:  { label: "Movement",        color: "#4cb89a", icon: "↑" },
      nourish:   { label: "Nourishment",     color: "#7ab86e", icon: "✦" },
      energy_q:  { label: "Energy Anchor",   color: "#f0c040", icon: "☀" },
      wins:      { label: "Body Wins",       color: "#4caac9", icon: "★" },
      recharge:  { label: "Recharge",        color: "#7a4cc9", icon: "◆" },
      tomorrow:  { label: "Tomorrow",        color: "#c97a4c", icon: "→" },
      weekly:    { label: "Weekly Check-In", color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "movement",  label: "Movement",        q: "What movement will you do today? Be specific — type, duration, time.", color: "#4cb89a", rows: 2 },
      { id: "nourish",   label: "Nourishment",     q: "How will you nourish your body today? Think food, water, sleep.", color: "#7ab86e", rows: 2 },
      { id: "energy_q",  label: "Energy Anchor",   q: loftyQ, color: "#f0c040", hint: "Let this question guide how you treat your body today.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "wins",     label: "Body Wins",   q: "3 ways you took care of your body today — even small things count.", color: "#4caac9", rows: 3 },
      { id: "recharge", label: "Recharge",    q: "How will you wind down and prepare your body for recovery tonight?", color: "#7a4cc9", rows: 2 },
      { id: "tomorrow", label: "Tomorrow",    q: "One health habit you'll prioritize tomorrow.", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Check-In", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  gratitude: {
    id: 'gratitude',
    name: 'Gratitude Journal',
    icon: '✿',
    color: '#e8836e',
    colorRgb: '232,131,110',
    description: 'Daily appreciation, joy, and abundance',
    tagline: 'What you notice, you multiply.',
    scoreLabels: ["", "Closed", "Heavy", "Flat", "Distracted", "Neutral", "Present", "Open", "Warm", "Grateful", "Radiant"],
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How open and receptive does your heart feel this morning?',
    scoreEveningQ: 'How full does your heart feel right now?',
    trendTitle: 'Gratitude Over Time',
    loftyQuestions: [
      "Why is my life so rich with things worth appreciating?",
      "Why does gratitude come so naturally to me?",
      "Why do I notice beauty even in ordinary moments?",
      "Why does appreciation open more doors for me?",
      "Why am I so aware of how much I already have?",
      "Why do I find reasons to be grateful even on hard days?",
      "Why does a grateful heart attract more to be grateful for?",
      "Why do I experience such joy in the simple things?",
      "Why does gratitude make me feel so alive?",
      "Why am I surrounded by people who enrich my life?",
      "Why does my sense of abundance keep growing?",
      "Why do I feel so blessed by what I have right now?",
      "Why does thankfulness feel like my natural state?",
      "Why am I so good at finding the gift in difficulty?",
      "Why does my gratitude practice deepen every day?",
      "Why do I attract so many experiences worth celebrating?",
      "Why does appreciating others make my own life fuller?",
      "Why is my capacity for wonder always expanding?",
      "Why do I feel genuinely lucky so often?",
      "Why does recognizing goodness make me want to create more of it?",
      "Why do the smallest kindnesses move me so deeply?",
      "Why do I see how interconnected all good things are?",
      "Why does my gratitude ripple outward and return multiplied?",
      "Why is appreciation the lens that makes everything sharper?",
      "Why do I feel more grateful now than I ever have before?",
    ],
    weeklyPrompts: [
      "What is something you've taken for granted this week that deserves real acknowledgment?",
      "Write a gratitude letter to someone who shaped you — you don't have to send it.",
      "What difficulty from the past are you now grateful for? What did it give you?",
      "Where did unexpected beauty show up this week?",
      "Who in your life makes things quietly easier? Have you told them?",
      "What about your body deserves more appreciation than you give it?",
      "Describe a moment from this week that, if you had missed it, you would have regretted.",
      "What ordinary thing in your life would feel like a miracle to a past version of you?",
      "What has the world given you this week that you didn't earn?",
      "Write 10 things you're grateful for that money cannot buy.",
      "Where did grace show up for you recently — something that went right without your effort?",
      "What would your life look like without one thing you currently have? Does imagining that change anything?",
      "If gratitude were a practice rather than a feeling, how would you deepen yours?",
    ],
    fieldMeta: {
      morning_g: { label: "Morning Gratitude", color: "#e8836e", icon: "✿" },
      gift:      { label: "Hidden Gift",       color: "#c97a9b", icon: "✦" },
      person:    { label: "Appreciate Someone",color: "#7ab86e", icon: "♡" },
      evening_g: { label: "Evening Gratitude", color: "#f0c040", icon: "✿" },
      shifted:   { label: "What Shifted",      color: "#4caac9", icon: "→" },
      weekly:    { label: "Weekly Reflection", color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "morning_g", label: "Morning Gratitude", q: "Name 3 things you're grateful for right now. Be specific — not 'family', but why, and what happened.", color: "#e8836e", rows: 3 },
      { id: "gift",      label: "Hidden Gift",       q: "What challenge in your life right now might actually be carrying a gift? Look for it.", color: "#c97a9b", rows: 2 },
      { id: "lofty_q",  label: "Today's Question",  q: loftyQ, color: "#f0c040", hint: "Let this sit in you today. Don't force an answer.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "evening_g", label: "Evening Gratitude", q: "What happened today that you want to remember feeling grateful for?", color: "#e8836e", rows: 2 },
      { id: "person",    label: "Appreciate Someone",q: "Who made your day a little better today — directly or indirectly? What did they do?", color: "#7ab86e", rows: 2 },
      { id: "shifted",   label: "What Shifted",      q: "Did gratitude change anything about how you moved through today? Even subtly?", color: "#4caac9", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Reflection", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  creativity: {
    id: 'creativity',
    name: 'Creativity Journal',
    icon: '◇',
    color: '#9b71d4',
    colorRgb: '155,113,212',
    description: 'Ideas, expression, and creative practice',
    tagline: 'Every day, something made.',
    scoreLabels: ["", "Blocked", "Stuck", "Foggy", "Restless", "Neutral", "Curious", "Inspired", "Flowing", "Electric", "Limitless"],
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How creatively alive do you feel this morning?',
    scoreEveningQ: 'How creatively expressed did you feel today?',
    trendTitle: 'Creative Energy Over Time',
    loftyQuestions: [
      "Why do ideas flow to me so freely?",
      "Why is my creative voice so distinct and needed?",
      "Why do I show up to create even when it's hard?",
      "Why does my work keep getting more honest and alive?",
      "Why am I so good at finishing what I start?",
      "Why does the creative process feel like play to me?",
      "Why do I trust my instincts when making creative decisions?",
      "Why does my output keep improving with each attempt?",
      "Why does inspiration find me wherever I am?",
      "Why do I have such a rich inner world to draw from?",
      "Why do I make time for creativity no matter how busy life gets?",
      "Why does my work resonate with people who need it?",
      "Why am I becoming bolder in my creative expression?",
      "Why do constraints make me more creative, not less?",
      "Why is every 'failure' in my work just a step to something better?",
      "Why does my creative confidence grow every day?",
      "Why do I attract collaborators and ideas that elevate my work?",
      "Why is my unique perspective exactly what the world needs?",
      "Why do I return to my creative practice like breathing?",
      "Why does making things make me more fully myself?",
      "Why do I see creative possibilities everywhere I look?",
      "Why do I keep expanding what I believe I'm capable of?",
      "Why does momentum build so naturally in my creative life?",
      "Why is shipping imperfect work better than never showing up?",
      "Why do I feel most alive when I'm deep in the act of making?",
    ],
    weeklyPrompts: [
      "What did you make or contribute to this week, however small? Describe it honestly.",
      "Where did fear or perfectionism show up in your creative work this week? What did you do with it?",
      "What artist, maker, or creator is inspiring you right now? What specifically do you admire?",
      "Describe your creative process this week — not the output, the process itself.",
      "What idea has been living in your head that you haven't acted on yet? What's stopping you?",
      "What would you create if you knew no one would judge it? Why aren't you doing that?",
      "What creative habit, if done daily for a year, would most change your work?",
      "Where did you play this week? Where did you get too serious?",
      "What constraints or limitations actually pushed your creativity this week?",
      "What piece of work (yours or someone else's) stopped you this week? Why?",
      "What does your creative voice sound like when it's most honest? Are you letting it?",
      "What would you make if time and skill were no object? What's the smallest version of that you could start today?",
      "What creative risk are you most proud of taking recently? What's the next one?",
    ],
    fieldMeta: {
      spark:    { label: "Creative Spark",    color: "#9b71d4", icon: "◇" },
      make:     { label: "Today I'll Make",   color: "#f0c040", icon: "✦" },
      created:  { label: "What I Made",       color: "#4cb89a", icon: "→" },
      obstacle: { label: "What Blocked Me",   color: "#c97a4c", icon: "◆" },
      tomorrow: { label: "Tomorrow's Seed",   color: "#e8836e", icon: "✿" },
      weekly:   { label: "Weekly Creative Audit", color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "spark", label: "Creative Spark",  q: "What idea, image, phrase, or feeling is alive in you this morning? Don't edit it — just capture it.", color: "#9b71d4", rows: 3 },
      { id: "make",  label: "Today I'll Make", q: "What one creative act will you commit to today? Be specific — what, when, for how long.", color: "#f0c040", rows: 2 },
      { id: "lofty_q", label: "Today's Question", q: loftyQ, color: "#9b71d4", hint: "Let this question open something in you. Return to it during the day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "created",  label: "What I Made",     q: "What did you create, contribute, or express today? Count everything — a conversation, a decision, a sketch.", color: "#4cb89a", rows: 2 },
      { id: "obstacle", label: "What Blocked Me", q: "What stopped you or slowed you today? Resistance, distraction, self-doubt — name it specifically.", color: "#c97a4c", rows: 2 },
      { id: "tomorrow", label: "Tomorrow's Seed", q: "One idea, question, or image to carry into tomorrow's creative session.", color: "#e8836e", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Creative Audit", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },
};
