// Journal-specific chapter text — each journal has its own arc language
export const JOURNAL_CHAPTERS = {
  wealth: {
    1: {
      name: "Awareness", days: "Days 1–30",
      opening: "Welcome. You've chosen to begin something rare — a daily practice with money that goes deeper than numbers. For the next thirty days, this journal is your private space to be completely honest about what wealth means to you, where it feels close, and where it feels impossibly far away.",
      expectation: "There's nothing to fix yet. Nothing to prove. You're simply here to look — to let old beliefs rise to the surface and be named. Some of what comes up will feel heavy. Some will surprise you with its quiet beauty. Let all of it be here. This is where the real work begins, and it begins with you, exactly as you are.",
      goals: [
        "Let the stories you carry about money finally be heard",
        "Create a morning and evening ritual that belongs only to you",
        "Begin to see where inherited beliefs end and your truth begins",
      ],
    },
    2: {
      name: "Action", days: "Days 31–60",
      opening: "You've spent thirty days looking honestly at yourself, and that is not a small thing. Now you're being invited into the next room — where the seeing becomes doing. This is where the ritual deepens. Where you bring your intentions into contact with the actual world.",
      expectation: "This chapter will ask more of you. There will be days when the momentum feels real and days when it disappears entirely. Both are part of the same practice. The ritual is not about feeling ready — it's about returning to this space regardless. You've already shown you can do that. Now let it compound.",
      goals: [
        "Bring one deliberate act of wealth-building into each week",
        "Close the distance between what you believe and how you live",
        "Let yourself become someone whose actions match their intentions",
      ],
    },
    3: {
      name: "Manifestation", days: "Days 61–90",
      opening: "Sixty days. You have kept returning to this ritual when nothing required it of you except your own commitment. Something has been building quietly inside that — a new way of carrying yourself around money, a new voice when you think about what's possible. You may not have named it yet. This final chapter is where you do.",
      expectation: "These last thirty days aren't about doing more. They're about receiving what the practice has already given you — and anchoring it so deeply into who you are that it travels with you beyond Day 90. The ritual doesn't end here. It graduates into your life.",
      goals: [
        "Receive the shift that's already happened — let yourself see it",
        "Anchor your new financial identity as something permanent",
        "Carry this practice forward as a way of living, not a program",
      ],
    },
  },

  motivational: {
    1: {
      name: "Awareness", days: "Days 1–30",
      opening: "You're here. That already says something about you. This journal is an invitation to step into a daily ritual — a quiet, private practice where you get to be completely honest about what drives you, what holds you back, and who you're becoming when no one is watching.",
      expectation: "For the next thirty days, nothing is required of you except presence. You don't need to be inspired. You don't need to feel ready. Some days in this chapter will crackle with energy. Others will feel flat and ordinary. Both are exactly right. This ritual isn't built on peak moments — it's built on showing up, again and again, in the ordinary ones.",
      goals: [
        "Give voice to what truly fuels you — and what quietly drains you",
        "Let this daily ritual become your anchor, not your performance",
        "Begin hearing your own story more honestly and more generously",
      ],
    },
    2: {
      name: "Action", days: "Days 31–60",
      opening: "For a full month, you've been building the foundation — watching yourself, naming things, showing up in the quiet. Now the ritual shifts. You're being invited into something more demanding and more rewarding: the place where intention becomes movement, where the person you've been seeing starts to actually appear in the world.",
      expectation: "There will come a moment in this chapter — around Week 5 — where the practice feels harder for no clear reason. That is not a sign to stop. That is the exact threshold you came here to cross. The ritual holds you here. Trust it. You've already proven you can return to it when the day is easy. Now you'll discover you can return when it isn't.",
      goals: [
        "Let growth be the choice you make before comfort gets a vote",
        "Build a consistency so steady it no longer needs motivation to run",
        "Watch yourself become — through action, not intention alone",
      ],
    },
    3: {
      name: "Manifestation", days: "Days 61–90",
      opening: "You have been practicing for sixty days. Not perfectly — no one does this perfectly — but faithfully. And something faithful over sixty days leaves a mark that can't be undone. You are not the same person who opened this journal on Day 1. This final chapter is about meeting that person face to face.",
      expectation: "What happens in these last thirty days is less about new effort and more about recognition. The transformation isn't waiting to happen — it has been happening, quietly, in every single return to this page. Now you get to own it. To claim it. To let it be true without waiting for more proof.",
      goals: [
        "Meet the version of yourself that sixty days of practice has built",
        "Claim the identity you've been growing into as simply who you are",
        "Let this ritual become not something you do, but something you are",
      ],
    },
  },

  health: {
    1: {
      name: "Awareness", days: "Days 1–30",
      opening: "Welcome to the beginning of something that most people never attempt: a daily ritual of honest attention to your body. Not to fix it. Not to push it. Just to listen — carefully, patiently, without judgment — to what it has been trying to tell you for longer than you might realize.",
      expectation: "Your body holds more wisdom than any plan or program. This chapter asks you to slow down enough to hear it. Some of what you notice will be uncomfortable. Some will be tender. Some will feel like finally being understood. Whatever arises, it belongs here. This ritual has room for all of it — and so do you.",
      goals: [
        "Begin truly hearing how your body feels, not how you think it should",
        "Create a morning and evening space where your body is welcomed",
        "Discover what genuinely restores you versus what merely distracts",
      ],
    },
    2: {
      name: "Action", days: "Days 31–60",
      opening: "You have spent a month learning to listen. Now the ritual deepens into something even more intimate: responding. This chapter is the practice of keeping promises to your body — small ones, consistent ones, made in the quiet of this space and honored in the hours beyond it.",
      expectation: "There will be days when movement feels like a gift and days when it feels like friction. Both are the practice. This chapter asks you to show up especially on the friction days — not to push through, but to honor the commitment you've made to yourself. That is what transforms a journal into a ritual, and a ritual into a life.",
      goals: [
        "Move through the world with intention rather than just momentum",
        "Keep the promises your body has asked you to keep",
        "Build a practice that is yours — not borrowed from someone else's plan",
      ],
    },
    3: {
      name: "Manifestation", days: "Days 61–90",
      opening: "Sixty days of returning to your body with honesty and care. What was once effort has become habit. What was once habit is becoming trust — a deep, earned trust between you and the body that carries you through everything. You are entering the final chapter of this ritual, and it is asking you to receive.",
      expectation: "These last thirty days are not about doing more. They're about letting the changes you've already made land fully in your sense of who you are. The ritual has been working even when you couldn't feel it. This chapter is where you finally see that — and let yourself be changed by the seeing.",
      goals: [
        "Receive the trust your body is offering you — you've earned it",
        "Recognize yourself as someone who honors the body, not fights it",
        "Carry this sacred attention with you beyond the final page",
      ],
    },
  },

  gratitude: {
    1: {
      name: "Awareness", days: "Days 1–30",
      opening: "You've stepped into a practice that is both ancient and quietly radical: the daily ritual of noticing what is good. Not performing positivity. Not pretending the hard things away. But choosing, day after day, to look for what is real and beautiful and already here — waiting, patiently, to be seen.",
      expectation: "Some days the gratitude will arrive easily, like opening a window into warmth. Other days it will feel distant, even hollow. Both are the practice. The ritual isn't asking you to feel grateful — it's asking you to look. What you find when you look, even on the hard days, will begin to change you in ways you won't notice until they've already happened.",
      goals: [
        "Develop the quiet habit of looking for what is already good",
        "Let appreciation become the orientation you return to each morning and evening",
        "Begin to see the distance between what you have and what you've been noticing",
      ],
    },
    2: {
      name: "Action", days: "Days 31–60",
      opening: "For thirty days you have been learning to see. Now the ritual invites you into something that multiplies everything you've built: expression. Gratitude held inside is beautiful. Gratitude spoken, written, given — that is where it becomes something alive in the world and in your relationships.",
      expectation: "This chapter will sometimes bring unexpected tenderness — the ache of realizing how much beauty has been passing by unacknowledged. Let that ache be welcome. It is not sadness. It is the feeling of a heart that is opening wider than it has in a long time. The ritual holds space for all of it.",
      goals: [
        "Let what you feel become what you say and what you give",
        "Find the hidden gift inside even the difficult moments",
        "Deepen the connections that your gratitude practice is quietly nourishing",
      ],
    },
    3: {
      name: "Manifestation", days: "Days 61–90",
      opening: "Sixty days of choosing to look for what is good. Something has shifted in you — not dramatically, but in the way light shifts when the angle changes just slightly and suddenly everything looks different. The world you're moving through hasn't changed. But the way you inhabit it has. This final chapter is an invitation to fully arrive there.",
      expectation: "These last thirty days ask something beautiful of you: to stop reaching for gratitude and to simply live from it. Not as a practice you remember to do, but as the natural orientation of who you are now. The ritual has been building this in you all along. You are ready to receive it.",
      goals: [
        "Live from abundance as your native ground, not a destination",
        "Let gratitude move through your relationships like light through water",
        "Carry this open heart beyond Day 90 — it belongs to you now",
      ],
    },
  },

  creativity: {
    1: {
      name: "Awareness", days: "Days 1–30",
      opening: "Welcome to a ritual for the part of you that has always needed to make things. Not the polished, finished, presentable version of your creativity — the raw one. The one that's been waiting under the noise and the doubt and the waiting-until-you're-ready. This practice is for that part. It begins today, with exactly what you have.",
      expectation: "You will feel resistance in this chapter. There will be days when the blank page feels like a wall and your creative voice feels like a stranger. That is not a sign that you don't belong here — it is the precise sign that you do. Every creative practice begins exactly here, in this uncomfortable and necessary place. The ritual is your way through.",
      goals: [
        "Show up to make something before you feel ready — especially then",
        "Begin to hear your own creative voice beneath the critic's",
        "Notice what sparks something alive in you and what quietly dims it",
      ],
    },
    2: {
      name: "Action", days: "Days 31–60",
      opening: "Your creative voice is real. You've heard it — in the glimpses, in the unexpected moments, in the days when something flowed. Now the ritual asks you to stop waiting for those days and start creating the conditions for them. This chapter is about showing up with your hands, not just your intentions.",
      expectation: "You will make things you don't love. You will show up on days when nothing comes. You will hit a wall around Week 5 that makes you question whether this was ever a good idea. That wall is the doorway. The ritual exists precisely to walk you through it — not around it. What's on the other side is a version of yourself you haven't met yet.",
      goals: [
        "Make something every day — imperfect, unfinished, real",
        "Release it before it's ready and discover what that teaches you",
        "Become someone who creates as a way of living, not a way of waiting",
      ],
    },
    3: {
      name: "Manifestation", days: "Days 61–90",
      opening: "You have been returning to this ritual for sixty days — through the resistance, through the dry spells, through the moments when your creative voice was loud and the many more when it was quiet. Something that began as a practice has become a part of you. This final chapter is an invitation to recognize it as such, and to stop treating it like a project you might abandon.",
      expectation: "These last thirty days ask something of you that may be harder than anything in the chapters before: to receive what you've built, to acknowledge that your voice is real, and to claim your creative identity without waiting for someone else's permission. The ritual has been preparing you for exactly this moment.",
      goals: [
        "Claim your creative voice as real, distinct, and fully yours",
        "Let sixty days of making become the proof you've been looking for",
        "Carry this practice forward as a permanent part of how you live",
      ],
    },
  },
};

export function getChapterNumber(journeyDay) {
  if (journeyDay <= 30) return 1;
  if (journeyDay <= 60) return 2;
  return 3;
}

export const STREAK_MILESTONES = [
  { days: 3,  message: "Three days. The ritual is taking root." },
  { days: 7,  message: "One week. Something is shifting." },
  { days: 14, message: "Two weeks in. The practice is finding its rhythm." },
  { days: 21, message: "Twenty-one days. Habits form in the quiet." },
  { days: 30, message: "A full month. You've crossed a threshold." },
  { days: 60, message: "Sixty days of showing up. This is who you are now." },
  { days: 90, message: "Ninety days. The journey is complete — and just beginning." },
];

const SCORE_LABELS_WEALTH = ["", "Anxious", "Stressed", "Uneasy", "Uncertain", "Neutral", "Okay", "Hopeful", "Confident", "Abundant", "Unstoppable"];
const SCORE_LABELS_MOTIV  = ["", "Defeated", "Drained", "Flat", "Restless", "Neutral", "Stirring", "Driven", "Focused", "Fired Up", "Unstoppable"];
const SCORE_COLORS = ["", "#c94c4c", "#c96a4c", "#c9884c", "#c9a44c", "#a8a868", "#7ab86e", "#5cb87a", "#4cb89a", "#4caac9", "#f0c040"];

export const JOURNALS = {
  wealth: {
    id: 'wealth',
    name: 'Wealth Journal',
    icon: '◆',
    color: '#f0c040',
    colorRgb: '240,192,64',
    description: '90-day financial mindset practice',
    tagline: 'Where money meets meaning.',
    scoreLabels: SCORE_LABELS_WEALTH,
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How do you feel about money this morning?',
    scoreEveningQ: 'How do you feel about money right now, end of day?',
    trendTitle: 'Money Mindset Over Time',
    loftyQuestions: [
      "Why does wealth come to me so naturally?",
      "Why am I so good at spotting opportunity?",
      "Why does money flow to me from expected and unexpected sources?",
      "Why do I always have more than enough?",
      "Why is building wealth so enjoyable for me?",
      "Why do people gladly pay for the value I create?",
      "Why am I so confident with financial decisions?",
      "Why does abundance feel so normal to me?",
      "Why do the right opportunities find me at the right time?",
      "Why is it so easy for me to save and invest wisely?",
      "Why do I attract people who help me grow financially?",
      "Why does my income keep increasing?",
      "Why am I so good at turning ideas into income?",
      "Why do I deserve financial freedom?",
      "Why does my relationship with money keep getting healthier?",
      "Why am I so disciplined with wealth-building habits?",
      "Why does my net worth grow while I sleep?",
      "Why do I make money decisions from abundance, not fear?",
      "Why is generosity so natural when wealth flows to me?",
      "Why do I trust myself completely with large sums of money?",
      "Why do my skills become more valuable every year?",
      "Why is financial education so fascinating to me?",
      "Why do I see possibility where others see limitation?",
      "Why does every setback move me closer to a breakthrough?",
      "Why am I becoming the person who earns at the next level?",
      "Why do I release old money stories so easily?",
      "Why is wealth just a natural byproduct of who I'm becoming?",
      "Why do I take action on financial goals without hesitation?",
      "Why does compound growth work so powerfully in my favor?",
      "Why am I already wealthier than I was yesterday?",
    ],
    weeklyPrompts: [
      "Income Ceiling Audit: What number do you believe is 'the most someone like you' can earn? Who told you that?",
      "What did you learn about money, investing, or financial systems this week? One takeaway.",
      "'I don't deserve more money because...' — Write honestly, then write the counter-evidence.",
      "Write 3 sentences from you 5 years from now, looking back at this week.",
      "Top 3 ways you created value this week. Which has the most growth potential?",
      "If money were a person, how would you describe your relationship right now?",
      "What financial skill would change everything? What's your plan to learn it?",
      "What % of this week's spending went toward things that genuinely matter?",
      "Are you spending time with people who expand or shrink your financial vision?",
      "What are you most afraid of with money? Is that fear protecting or trapping you?",
      "One financial thing you used to dream about but now take for granted.",
      "If you HAD to 10x your income in 3 years, what changes starting Monday?",
      "Describe the person who naturally earns at the level you're building toward.",
    ],
    fieldMeta: {
      visualize: { label: "Visualize",        color: "#f0c040", icon: "☀" },
      gratitude:  { label: "Money Gratitude", color: "#7a4cc9", icon: "✦" },
      lofty_a:    { label: "Lofty Answer",    color: "#a8c94c", icon: "→" },
      value:      { label: "Value Created",   color: "#c97a4c", icon: "◆" },
      weekly:     { label: "Weekly Deep Dive",color: "#c94c6e", icon: "★" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "visualize", label: "Visualize",             q: "Close your eyes for 60 seconds. See one specific scene from the life you're building. Describe it.", color: "#f0c040", rows: 2 },
      { id: "gratitude", label: "Money Gratitude",       q: "3 financial things you're grateful for right now, no matter how small.", color: "#7a4cc9", rows: 3 },
      { id: "lofty_q",   label: "Today's Lofty Question",q: loftyQ, color: "#a8c94c", hint: "Sit with this question. Let your brain search for answers all day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "lofty_a", label: "Lofty Answer",    q: `Your brain has been working on this all day:\n\n"${loftyQ}"\n\nWhat answers did it find?`, color: "#a8c94c", rows: 2 },
      { id: "value",   label: "Value Created",   q: "How did you create value for others today?", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Deep Dive", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  motivational: {
    id: 'motivational',
    name: 'Motivational Journal',
    icon: '★',
    color: '#a8c94c',
    colorRgb: '168,201,76',
    description: 'Daily mindset, growth, and momentum',
    tagline: 'Build the mind that builds the life.',
    scoreLabels: SCORE_LABELS_MOTIV,
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How motivated and alive do you feel this morning?',
    scoreEveningQ: 'How driven and energized do you feel right now?',
    trendTitle: 'Motivation Over Time',
    loftyQuestions: [
      "Why do I keep showing up even when it's hard?",
      "Why is growth my natural state?",
      "Why am I so resilient?",
      "Why do I embrace discomfort as part of my progress?",
      "Why does consistency come naturally to me?",
      "Why do I believe in myself more every day?",
      "Why do my habits compound into extraordinary results?",
      "Why do I attract people who push me to grow?",
      "Why do I turn obstacles into opportunities?",
      "Why does discipline feel like freedom to me?",
      "Why am I becoming the best version of myself?",
      "Why do I complete what I start?",
      "Why is my potential limitless?",
      "Why do I show up fully every single day?",
      "Why does my mindset get stronger through challenges?",
      "Why do I choose growth over comfort?",
      "Why do I inspire others simply by becoming my best self?",
      "Why do I take full responsibility for my results?",
      "Why does momentum build naturally for me?",
      "Why am I exactly where I need to be right now?",
      "Why do small daily actions create massive change for me?",
      "Why do I trust the process even when results are slow?",
      "Why is my best always getting better?",
      "Why do I pursue excellence without waiting for perfect conditions?",
      "Why do I use every day as a chance to level up?",
    ],
    weeklyPrompts: [
      "What's one belief you're still letting limit you? How would you act if you dropped it?",
      "Rate your consistency this week 1–10. What would make it a 10 next week?",
      "Who in your life models the energy and discipline you want? What can you learn from them?",
      "What habit, if done daily for a year, would change your life most?",
      "Where did you choose comfort over growth this week? Was it worth it?",
      "What does your future self need you to do right now that your current self is avoiding?",
      "What's the difference between who you are now and who you're becoming?",
      "If you could give advice to yourself from 1 year ago, what would it be?",
      "What's the story you keep telling yourself that's holding you back? Rewrite it.",
      "Name one hard thing you did this week that you're proud of.",
      "What would you attempt if you knew you couldn't fail?",
      "Who do you need to become to achieve the goals you've set?",
    ],
    fieldMeta: {
      intention:  { label: "Today's Intention", color: "#f0c040", icon: "→" },
      affirmation:{ label: "Affirmation",        color: "#4caac9", icon: "✦" },
      wins:       { label: "Wins",               color: "#4cc97a", icon: "★" },
      learning:   { label: "Learning",           color: "#7a4cc9", icon: "◆" },
      tomorrow:   { label: "Tomorrow",           color: "#c97a4c", icon: "↑" },
      weekly:     { label: "Weekly Reflection",  color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "intention",   label: "Today's Intention", q: "What's the one thing that would make today a win? Be specific.", color: "#f0c040", rows: 2 },
      { id: "affirmation", label: "Affirmation",        q: "Complete this: I am becoming someone who...", color: "#4caac9", rows: 2 },
      { id: "lofty_q",     label: "Today's Question",   q: loftyQ, color: "#a8c94c", hint: "Let this question sit with you all day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "wins",     label: "Wins",              q: "List 3 wins from today — small or large, they all count.", color: "#4cc97a", rows: 3 },
      { id: "learning", label: "Learning",          q: "What did today teach you about yourself?", color: "#7a4cc9", rows: 2 },
      { id: "tomorrow", label: "Tomorrow",          q: "One thing you'll do better or differently tomorrow.", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Reflection", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  health: {
    id: 'health',
    name: 'Health Journal',
    icon: '♡',
    color: '#4cb89a',
    colorRgb: '76,184,154',
    description: 'Body, energy, and daily habits',
    tagline: 'Honor the body. Trust the process.',
    scoreLabels: ["", "Depleted", "Drained", "Heavy", "Sluggish", "Neutral", "Okay", "Energized", "Strong", "Vibrant", "Unstoppable"],
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How does your body feel this morning?',
    scoreEveningQ: 'How did your body hold up today?',
    trendTitle: 'Energy Over Time',
    loftyQuestions: [
      "Why does my body feel so strong and capable?",
      "Why does healthy living come naturally to me?",
      "Why do I crave movement and feel good after exercise?",
      "Why does my energy stay high throughout the day?",
      "Why do I sleep deeply and wake up refreshed?",
      "Why do I make food choices that nourish me?",
      "Why does my body recover so well?",
      "Why am I becoming healthier every single day?",
      "Why do I listen to and trust my body?",
      "Why does consistency with my health habits feel effortless?",
      "Why do I attract the energy and vitality I want?",
      "Why does my body naturally find its ideal state?",
      "Why do small healthy choices add up so powerfully for me?",
      "Why do I enjoy taking care of myself?",
      "Why does rest and recovery feel like strength?",
      "Why do I breathe deeply and move with ease?",
      "Why is building healthy habits one of my greatest investments?",
      "Why do I wake up excited to take care of my body today?",
      "Why does physical strength translate into mental strength for me?",
      "Why do I make time for movement no matter how busy I am?",
      "Why does hydration and nutrition come so naturally to me?",
      "Why do I feel more alive and vibrant each week?",
      "Why do I show up for my health even when motivation dips?",
      "Why does my body thank me when I treat it well?",
      "Why is long-term health my most important asset?",
    ],
    weeklyPrompts: [
      "How did your energy levels track this week? What patterns do you notice?",
      "What's one health habit that served you well — and one you want to strengthen?",
      "If your body could talk, what would it say to you right now?",
      "Where did you choose convenience over health? Was it worth it?",
      "What does 'feeling healthy' actually mean to you? Has that definition shifted?",
      "Rate your sleep quality this week 1–10. What would make it a 10 next week?",
      "What's one belief about your body that you're ready to let go of?",
      "How has your energy level shaped your mood and decisions this week?",
      "What would your life look like if you were at your physical best?",
      "Name one hard health habit you kept this week that you're proud of.",
      "What's the gap between how you want to feel and how you actually feel? What's the bridge?",
      "Who models the level of health and vitality you want? What can you learn from them?",
      "If you treated your body like your most prized possession, what would change?",
    ],
    fieldMeta: {
      movement:  { label: "Movement",        color: "#4cb89a", icon: "↑" },
      nourish:   { label: "Nourishment",     color: "#7ab86e", icon: "✦" },
      energy_q:  { label: "Energy Anchor",   color: "#f0c040", icon: "☀" },
      wins:      { label: "Body Wins",       color: "#4caac9", icon: "★" },
      recharge:  { label: "Recharge",        color: "#7a4cc9", icon: "◆" },
      tomorrow:  { label: "Tomorrow",        color: "#c97a4c", icon: "→" },
      weekly:    { label: "Weekly Check-In", color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "movement",  label: "Movement",        q: "What movement will you do today? Be specific — type, duration, time.", color: "#4cb89a", rows: 2 },
      { id: "nourish",   label: "Nourishment",     q: "How will you nourish your body today? Think food, water, sleep.", color: "#7ab86e", rows: 2 },
      { id: "energy_q",  label: "Energy Anchor",   q: loftyQ, color: "#f0c040", hint: "Let this question guide how you treat your body today.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "wins",     label: "Body Wins",   q: "3 ways you took care of your body today — even small things count.", color: "#4caac9", rows: 3 },
      { id: "recharge", label: "Recharge",    q: "How will you wind down and prepare your body for recovery tonight?", color: "#7a4cc9", rows: 2 },
      { id: "tomorrow", label: "Tomorrow",    q: "One health habit you'll prioritize tomorrow.", color: "#c97a4c", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Check-In", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  gratitude: {
    id: 'gratitude',
    name: 'Gratitude Journal',
    icon: '✿',
    color: '#e8836e',
    colorRgb: '232,131,110',
    description: 'Daily appreciation, joy, and abundance',
    tagline: 'What you notice, you multiply.',
    scoreLabels: ["", "Closed", "Heavy", "Flat", "Distracted", "Neutral", "Present", "Open", "Warm", "Grateful", "Radiant"],
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How open and receptive does your heart feel this morning?',
    scoreEveningQ: 'How full does your heart feel right now?',
    trendTitle: 'Gratitude Over Time',
    loftyQuestions: [
      "Why is my life so rich with things worth appreciating?",
      "Why does gratitude come so naturally to me?",
      "Why do I notice beauty even in ordinary moments?",
      "Why does appreciation open more doors for me?",
      "Why am I so aware of how much I already have?",
      "Why do I find reasons to be grateful even on hard days?",
      "Why does a grateful heart attract more to be grateful for?",
      "Why do I experience such joy in the simple things?",
      "Why does gratitude make me feel so alive?",
      "Why am I surrounded by people who enrich my life?",
      "Why does my sense of abundance keep growing?",
      "Why do I feel so blessed by what I have right now?",
      "Why does thankfulness feel like my natural state?",
      "Why am I so good at finding the gift in difficulty?",
      "Why does my gratitude practice deepen every day?",
      "Why do I attract so many experiences worth celebrating?",
      "Why does appreciating others make my own life fuller?",
      "Why is my capacity for wonder always expanding?",
      "Why do I feel genuinely lucky so often?",
      "Why does recognizing goodness make me want to create more of it?",
      "Why do the smallest kindnesses move me so deeply?",
      "Why do I see how interconnected all good things are?",
      "Why does my gratitude ripple outward and return multiplied?",
      "Why is appreciation the lens that makes everything sharper?",
      "Why do I feel more grateful now than I ever have before?",
    ],
    weeklyPrompts: [
      "What is something you've taken for granted this week that deserves real acknowledgment?",
      "Write a gratitude letter to someone who shaped you — you don't have to send it.",
      "What difficulty from the past are you now grateful for? What did it give you?",
      "Where did unexpected beauty show up this week?",
      "Who in your life makes things quietly easier? Have you told them?",
      "What about your body deserves more appreciation than you give it?",
      "Describe a moment from this week that, if you had missed it, you would have regretted.",
      "What ordinary thing in your life would feel like a miracle to a past version of you?",
      "What has the world given you this week that you didn't earn?",
      "Write 10 things you're grateful for that money cannot buy.",
      "Where did grace show up for you recently — something that went right without your effort?",
      "What would your life look like without one thing you currently have? Does imagining that change anything?",
      "If gratitude were a practice rather than a feeling, how would you deepen yours?",
    ],
    fieldMeta: {
      morning_g: { label: "Morning Gratitude", color: "#e8836e", icon: "✿" },
      gift:      { label: "Hidden Gift",       color: "#c97a9b", icon: "✦" },
      person:    { label: "Appreciate Someone",color: "#7ab86e", icon: "♡" },
      evening_g: { label: "Evening Gratitude", color: "#f0c040", icon: "✿" },
      shifted:   { label: "What Shifted",      color: "#4caac9", icon: "→" },
      weekly:    { label: "Weekly Reflection", color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "morning_g", label: "Morning Gratitude", q: "Name 3 things you're grateful for right now. Be specific — not 'family', but why, and what happened.", color: "#e8836e", rows: 3 },
      { id: "gift",      label: "Hidden Gift",       q: "What challenge in your life right now might actually be carrying a gift? Look for it.", color: "#c97a9b", rows: 2 },
      { id: "lofty_q",  label: "Today's Question",  q: loftyQ, color: "#f0c040", hint: "Let this sit in you today. Don't force an answer.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "evening_g", label: "Evening Gratitude", q: "What happened today that you want to remember feeling grateful for?", color: "#e8836e", rows: 2 },
      { id: "person",    label: "Appreciate Someone",q: "Who made your day a little better today — directly or indirectly? What did they do?", color: "#7ab86e", rows: 2 },
      { id: "shifted",   label: "What Shifted",      q: "Did gratitude change anything about how you moved through today? Even subtly?", color: "#4caac9", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Reflection", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },

  creativity: {
    id: 'creativity',
    name: 'Creativity Journal',
    icon: '◇',
    color: '#9b71d4',
    colorRgb: '155,113,212',
    description: 'Ideas, expression, and creative practice',
    tagline: 'Every day, something made.',
    scoreLabels: ["", "Blocked", "Stuck", "Foggy", "Restless", "Neutral", "Curious", "Inspired", "Flowing", "Electric", "Limitless"],
    scoreColors: SCORE_COLORS,
    scoreMorningQ: 'How creatively alive do you feel this morning?',
    scoreEveningQ: 'How creatively expressed did you feel today?',
    trendTitle: 'Creative Energy Over Time',
    loftyQuestions: [
      "Why do ideas flow to me so freely?",
      "Why is my creative voice so distinct and needed?",
      "Why do I show up to create even when it's hard?",
      "Why does my work keep getting more honest and alive?",
      "Why am I so good at finishing what I start?",
      "Why does the creative process feel like play to me?",
      "Why do I trust my instincts when making creative decisions?",
      "Why does my output keep improving with each attempt?",
      "Why does inspiration find me wherever I am?",
      "Why do I have such a rich inner world to draw from?",
      "Why do I make time for creativity no matter how busy life gets?",
      "Why does my work resonate with people who need it?",
      "Why am I becoming bolder in my creative expression?",
      "Why do constraints make me more creative, not less?",
      "Why is every 'failure' in my work just a step to something better?",
      "Why does my creative confidence grow every day?",
      "Why do I attract collaborators and ideas that elevate my work?",
      "Why is my unique perspective exactly what the world needs?",
      "Why do I return to my creative practice like breathing?",
      "Why does making things make me more fully myself?",
      "Why do I see creative possibilities everywhere I look?",
      "Why do I keep expanding what I believe I'm capable of?",
      "Why does momentum build so naturally in my creative life?",
      "Why is shipping imperfect work better than never showing up?",
      "Why do I feel most alive when I'm deep in the act of making?",
    ],
    weeklyPrompts: [
      "What did you make or contribute to this week, however small? Describe it honestly.",
      "Where did fear or perfectionism show up in your creative work this week? What did you do with it?",
      "What artist, maker, or creator is inspiring you right now? What specifically do you admire?",
      "Describe your creative process this week — not the output, the process itself.",
      "What idea has been living in your head that you haven't acted on yet? What's stopping you?",
      "What would you create if you knew no one would judge it? Why aren't you doing that?",
      "What creative habit, if done daily for a year, would most change your work?",
      "Where did you play this week? Where did you get too serious?",
      "What constraints or limitations actually pushed your creativity this week?",
      "What piece of work (yours or someone else's) stopped you this week? Why?",
      "What does your creative voice sound like when it's most honest? Are you letting it?",
      "What would you make if time and skill were no object? What's the smallest version of that you could start today?",
      "What creative risk are you most proud of taking recently? What's the next one?",
    ],
    fieldMeta: {
      spark:    { label: "Creative Spark",    color: "#9b71d4", icon: "◇" },
      make:     { label: "Today I'll Make",   color: "#f0c040", icon: "✦" },
      created:  { label: "What I Made",       color: "#4cb89a", icon: "→" },
      obstacle: { label: "What Blocked Me",   color: "#c97a4c", icon: "◆" },
      tomorrow: { label: "Tomorrow's Seed",   color: "#e8836e", icon: "✿" },
      weekly:   { label: "Weekly Creative Audit", color: "#c94c6e", icon: "✎" },
    },
    getMorningPrompts: (loftyQ) => [
      { id: "spark", label: "Creative Spark",  q: "What idea, image, phrase, or feeling is alive in you this morning? Don't edit it — just capture it.", color: "#9b71d4", rows: 3 },
      { id: "make",  label: "Today I'll Make", q: "What one creative act will you commit to today? Be specific — what, when, for how long.", color: "#f0c040", rows: 2 },
      { id: "lofty_q", label: "Today's Question", q: loftyQ, color: "#9b71d4", hint: "Let this question open something in you. Return to it during the day.", isQuestion: true },
    ],
    getEveningPrompts: (loftyQ, weeklyQ, isMonday) => [
      { id: "created",  label: "What I Made",     q: "What did you create, contribute, or express today? Count everything — a conversation, a decision, a sketch.", color: "#4cb89a", rows: 2 },
      { id: "obstacle", label: "What Blocked Me", q: "What stopped you or slowed you today? Resistance, distraction, self-doubt — name it specifically.", color: "#c97a4c", rows: 2 },
      { id: "tomorrow", label: "Tomorrow's Seed", q: "One idea, question, or image to carry into tomorrow's creative session.", color: "#e8836e", rows: 2 },
      ...(isMonday ? [{ id: "weekly", label: "Weekly Creative Audit", q: weeklyQ, color: "#c94c6e", weekly: true, rows: 3 }] : []),
    ],
  },
};
